//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Richi.Shop._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RJ_ADMINISTRADORES
    {
        public int RJ_ADMINISTRADORES_ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string EMAIL { get; set; }
        public string CONTRASENA { get; set; }
        public bool ESTADO { get; set; }
    }
}
