//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Richi.Shop._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RJ_CATEGORIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RJ_CATEGORIAS()
        {
            this.RJ_PUESTOS = new HashSet<RJ_PUESTOS>();
        }
    
        public int RJ_CATEGORIAS_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public bool ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RJ_PUESTOS> RJ_PUESTOS { get; set; }
    }
}
