//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Richi.Shop._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RJ_PUESTOS
    {
        public int RJ_PUESTOS_ID { get; set; }
        public string COMPANIA { get; set; }
        public string TIPO { get; set; }
        public byte[] LOGO { get; set; }
        public string URL { get; set; }
        public string POSICION { get; set; }
        public string UBICACION { get; set; }
        public int RJ_CATEGORIAS_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string EMAIL { get; set; }
        public bool PERMISOS_AFILIADOS { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FINAL { get; set; }
        public bool ESTADO { get; set; }
    
        public virtual RJ_CATEGORIAS RJ_CATEGORIAS { get; set; }
    }
}
